разметка без стилей
NataliiaValko/parcel-project-template pull request #48
Opened 2021-03-12 20:26 UTC by rovshaninho

2021-03-12 21:03 UTC, NataliiaValko requested changes

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
вот это под вопросом пока....я просто хз так ли это надо реализовать

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +<section>
секция это блок, поэтому дай ей класс swiper

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +  <div class="swiper-container">
в компонентах есть общие классы и контейнер  там уже есть...он один на всех и одинаковый, поэтому даем просто класс container и все. Стили ему не пишешь, они у же написаны

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +    <div class="swiper-wrapper">
swiper__wrapper

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +      <div class="swiper-slide">
как я понимаю слайд это блок у тебя поэтому класс slider

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +        <div class="slider-block">
slider__block

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +      </div>
он лишний

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +            src="../src/images/7-testimonials/testimonials-1- 1x.jpg"
одна точечка не лишняя вначале? и пробел в имени файла смущает...так вроде низзя. Так же плотность в аватарке пока под вопросом (Оставлю это тут для себя).

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +            alt=""
заполни

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +            <div class="slider-adress">
slider__address

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +      <div class="swiper-slide">
скопируй классы по комментам выше

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +    <div class="slider-point">
slider__point

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +    <div class="swiper-pagination"></div>
swiper__pagination

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
инклудом внизу индекса добавить. Сделаем отдельный паршал для скриптов общий или каждый сам себе...обсудим завтра

2021-03-12 21:03 UTC, NataliiaValko commented on src/partials/testimonials.html
> +<script>
сам скрипт должен лежать в файле джс....как я поняла...все что по скриптам на потом...коммент для меня

2021-03-12 21:03 UTC, closed without merging

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
Вынес в index, там где нормалайз и т.д. По идеи ему там и место. Все работает (+)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +<section>
(+)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +  <div class="swiper-container">
Это не общий контейнер, а класс со скрипта. (-)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +    <div class="swiper-wrapper">
Классы, которые прописанные в скрипте, пока оставлю как есть и без нижнего подчеркиванием, ибо сразу ломаются стили. (-)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +      <div class="swiper-slide">
swiper-slide класс тоже со скрипта, а ниже slider-block уже прописанный мной. (-)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +        <div class="slider-block">
(-)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +      </div>
на 72 строке закрывающий тег дива с классом swiper-slide, их там три штуки. То есть, на каждый блок. (-)

2021-03-14 11:27 UTC, rovshaninho commented on src/partials/testimonials.html
> +            src="../src/images/7-testimonials/testimonials-1- 1x.jpg"
Исправил (+)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +            alt=""
Сделал (+)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +            <div class="slider-adress">
(-)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +      <div class="swiper-slide">
(-)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +    <div class="slider-point">
(-)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +    <div class="swiper-pagination"></div>
(-)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
Так, вот с этим у меня проблема. Если выношу, то сразу перестает работать слайд. С этим моментом нужна будет помощь. Пока оставляю. (-)

2021-03-14 11:28 UTC, rovshaninho commented on src/partials/testimonials.html
> +<script>
Я понимаю, но опять же, это нужно решить вместо, ибо когда выносил, не работал скрипт. Возможно что-то неправильно сделал.